name: release

on:
  release:
    types: [published]

jobs:
  build_push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: build image and push
      run: |
        docker build . --tag ghcr.io/skovati/curl-ip:latest
        docker run ghcr.io/skovati/curl-ip:latest
        docker push ghcr.io/skovati/curl-ip:latest
